---
services:
  speedtest-tracker:
    image: lscr.io/linuxserver/speedtest-tracker:latest
    container_name: speedtest-tracker
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - APP_KEY=
      - APP_URL=
      - DB_CONNECTION=sqlite
      - SPEEDTEST_SCHEDULE=
      - SPEEDTEST_SERVERS=
      - DB_HOST= #optional
      - DB_PORT= #optional
      - DB_DATABASE= #optional
      - DB_USERNAME= #optional
      - DB_PASSWORD= #optional
      - DISPLAY_TIMEZONE=Etc/UTC #optional
      - PRUNE_RESULTS_OLDER_THAN=0 #optional
    volumes:
      - /path/to/speedtest-tracker/data:/config
    ports:
      - 75:80
    restart: unless-stopped


#Modified to Deployment:
#---------------------------->

---
services:
  speedtest-tracker:
    image: lscr.io/linuxserver/speedtest-tracker:latest
    container_name: speedtest-tracker
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=IN/IST
      - APP_KEY=
      - APP_URL=
      - DB_CONNECTION=sqlite
      - DISPLAY_TIMEZONE=IN/IST #optional
      - PRUNE_RESULTS_OLDER_THAN=0 #optional
    volumes:
      - /path/to/speedtest-tracker/data:/config
    ports:
      - 1020:80
    restart: unless-stopped